services:
  db:
    image: postgres:15.3-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: xsis
      TZ: UTC
      TZDATA: UTC
      PGTZ: UTC
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
